### ISSUE TITLE
Can you consider adding the method of attention transfer and neuron-selectivity-transfer?

### ISSUE THREAD

**Issue by Xiaocong6** [sseung0703/Knowledge_distillation_methods_wtih_Tensorflow#1]
Thanks a lot for the code!
I read some papers about distillation and noticed that the two methods are not compared in your code. Can you consider adding them? My programming skills are poor(*_*), I still need to learn from you.
attention transfer  https://arxiv.org/abs/1612.03928
neuron-selectivity-transfer https://arxiv.org/abs/1707.01219
In addition, I think it is better to  specify the structure of the student network and the teacher network in the form.
Thanks again.

**Comment by Xiaocong6** [comment]
sorry, I saw the network structure, I didn’t pay attention to the Korean part just now.

**Comment by sseung0703** [comment]
i have a plan for attention transfer but not sure for neuron-selectivity-transfer. and i will translate all part for English soon. :)

**Comment by sseung0703** [comment]
I added attention transfer. :)

**Comment by Xiaocong6** [comment]
Thanks a lot!
