### ISSUE TITLE
which is the paper for KD_EID?

### ISSUE THREAD

**Issue by guanfuchen** [sseung0703/Knowledge_distillation_methods_wtih_Tensorflow#14]
Great work!!! Which is the paper for KD_EID performing best?

**Comment by sseung0703** [comment]
Actually, It is not yet published or pre-printed.
There is related paper which is Korean domestic conference, but there is too less information.
I submitted paper which analyze KD-EID to journal.
So, if you want to refer KD-EID, you should wait.


Anyway, below line is MLA cite of Korean domestic conference paper I said above.

    이승현, and 송병철. "수학적 정의에 기반한 Singular value decomposition 가속화." 대한전자공학회 학술대회 (2019)


And, Actually the best method is MHGD at now. :)
