### ISSUE TITLE
TypeError: ResNet() missing 1 required positional argument: 'label'

### ISSUE THREAD

**Issue by CBHealth** [sseung0703/Knowledge_distillation_methods_wtih_Tensorflow#4]
Get an error after this argument of the tutorial: 
python3 train_w_distill.py --Distillation=None --train_dir=test --main_scope=Teacher

Same error for training the student. Any idea what to do about it?

Error message:

Traceback (most recent call last):

  File "train_w_distill.py", line 228, in <module>
    tf.app.run()
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train_w_distill.py", line 71, in main
    is_training, reuse = False, drop = True, Distillation = FLAGS.Distillation)
  File "train_w_distill.py", line 196, in MODEL
    end_points = network_fn(image, scope, is_training=is_training, reuse=reuse, drop = drop, Distill=Distillation)
  File "/home/user/deeplearning/Knowledge_distillation_methods_wtih_Tensorflow-master/nets/nets_factory.py", line 24, in network_fn
    return func(images, scope = scope, is_training=is_training, reuse = reuse, drop = drop, Distill=Distill)
TypeError: ResNet() missing 1 required positional argument: 'label'

I use Python3.6.7 and Tensorflow 1.13.1 CPU only on Ubuntu 18.04.
Thanks in advance!

**Comment by CBHealth** [comment]
I think I found the solution. Network trains now. Will commit after.

**Comment by sseung0703** [comment]
I'm sorry about many minor errors. But it is not so critical error and easy to fix.
I'll correct errors with a new knowledge distillation algorithm. :)

**Comment by CBHealth** [comment]
Don't worry. I will work through it and send you the corrected version.
Training with my computer just takes a little longer! Still a great
project.

Seung-Hyun Lee <notifications@github.com> schrieb am Mo., 17. Juni 2019,
4:04 nachm.:

**Comment by IssaIssa1** [comment]
> I think I found the solution. Network trains now. Will commit after.

I am trying to run the code using the pre_trained model, but I have the same problem. May you please clarify how you fixed it ?

**Comment by sseung0703** [comment]
I fixed the error. So I close this issue.
Thank you for your attention :)

**Comment by CBHealth** [comment]
Sure! Will upload it tonight. Latestly 6pm German time.

Issa Issa <notifications@github.com> schrieb am Di., 18. Juni 2019, 3:04
nachm.:

**Comment by CBHealth** [comment]
Pushed it into my fork.

Clara Butt <clara.butt@aiesec.net> schrieb am Di., 18. Juni 2019, 3:59
nachm.:

**Comment by CBHealth** [comment]
Do u know how to get there?

Clara Butt <clara.butt@aiesec.net> schrieb am Di., 18. Juni 2019, 6:11
nachm.:

**Comment by sseung0703** [comment]
You can find what I changed in the commit history. there are few lines changed in "train_w_distillation.py" and "net_factory.py"
